### PR TITLE
prometheus-k8s requires trust now

### PR DESCRIPTION
**Pull request by addyess**
must deploy `prometheus-k8s` with `--trust` now

### CODE REVIEW

**Comment by addyess** [comment]
@balbirthomas, it seems something has changed in `prometheus-k8s` preventing its deployment in microk8s.  Any ideas?

**Comment by balbirthomas** [comment]
> @balbirthomas, it seems something has changed in `prometheus-k8s` preventing its deployment in microk8s. Any ideas?

Hi @addyess just `--trust` which you seem to have noted above. I can see the integration tests are running now. I'll wait to see if they complete.

**Comment by addyess** [comment]
>  I'll wait to see if they complete.

@balbirthomas i've added juju-crashdump output to the integration tests for when the fail.  last failure the prometheus-k8s charm was in error trying to fetch the image resource.

**Comment by addyess** [comment]
but of course they work this time!! :)

**Pull request merged**
